// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.19.1
// source: ui.proto

/* eslint-disable */
import { Empty, EmptyRequest } from "./common"

export const protobufPackage = "cline"

/** Service for UI-related operations */
export type UiServiceDefinition = typeof UiServiceDefinition
export const UiServiceDefinition = {
	name: "UiService",
	fullName: "cline.UiService",
	methods: {
		/** Requests the extension to show the chat view */
		showChatView: {
			name: "showChatView",
			requestType: EmptyRequest,
			requestStream: false,
			responseType: Empty,
			responseStream: false,
			options: {},
		},
	},
} as const
