// AUTO-GENERATED FILE - DO NOT MODIFY DIRECTLY
// Generated by proto/build-proto.js

// Import all method implementations
import { registerMethod } from "./index"
import { askResponse } from "./askResponse"
import { cancelTask } from "./cancelTask"
import { clearTask } from "./clearTask"
import { deleteNonFavoritedTasks } from "./deleteNonFavoritedTasks"
import { deleteTasksWithIds } from "./deleteTasksWithIds"
import { documentCode } from "./documentCode"
import { executeCustomDirection } from "./executeCustomDirection"
import { exportTaskWithId } from "./exportTaskWithId"
import { getTaskHistory } from "./getTaskHistory"
import { newTask } from "./newTask"
import { reviewCode } from "./reviewCode"
import { showTaskWithId } from "./showTaskWithId"
import { taskCompletionViewChanges } from "./taskCompletionViewChanges"
import { taskFeedback } from "./taskFeedback"
import { toggleTaskFavorite } from "./toggleTaskFavorite"

// Register all task service methods
export function registerAllMethods(): void {
	// Register each method with the registry
	registerMethod("askResponse", askResponse)
	registerMethod("cancelTask", cancelTask)
	registerMethod("clearTask", clearTask)
	registerMethod("deleteNonFavoritedTasks", deleteNonFavoritedTasks)
	registerMethod("deleteTasksWithIds", deleteTasksWithIds)
	registerMethod("documentCode", documentCode)
	registerMethod("executeCustomDirection", executeCustomDirection)
	registerMethod("exportTaskWithId", exportTaskWithId)
	registerMethod("getTaskHistory", getTaskHistory)
	registerMethod("newTask", newTask)
	registerMethod("reviewCode", reviewCode)
	registerMethod("showTaskWithId", showTaskWithId)
	registerMethod("taskCompletionViewChanges", taskCompletionViewChanges)
	registerMethod("taskFeedback", taskFeedback)
	registerMethod("toggleTaskFavorite", toggleTaskFavorite)
}
